sudo: required

language: generic

services:
    - docker

# before_install:
# - docker build -t lyyjeren/backend -f ./backend/Dockerfile.dev ./backend
# - docker build -t lyyjeren/frontend -f ./frontend/Dockerfile.dev ./frontend
# - docker build -t lyyjeren/nginx -f ./nginx/Dockerfile.dev ./nginx

# script:
#     - docker run -e CI=true lyyjeren/frontend npm run start

branches:
    only: ['master', 'deploy']

after_success:
    - docker build -t lyyjeren/backend ./backend
    - docker build -t lyyjeren/frontend ./frontend
    - docker build -t lyyjeren/nginx ./nginx
    # login docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push image to docker hub
    - docker push lyyjeren/backend
    - docker push lyyjeren/frontend
    - docker push lyyjeren/nginx
