version: "3"
services:
  mongo:
    image: "mongo:4.2"
    env_file:
      - ./backend/.env_file
    ports:
      - 27017:27017
    volumes:
      - ./backend/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  backend:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    env_file:
      - ./backend/.env_file
    ports:
      - 8000:8000
    volumes:
      - /app/node_modules
      - ./backend:/app
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
  nginx:
    restart: always
    depends_on:
      - backend
      - frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
